/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#00201d",
        "on-tertiary-container": "#1f9c8f",
        "on-error": "#ffffff",
        "tertiary": "#001210",
        "on-secondary-container": "#00476e",
        "inverse-surface": "#213145",
        "surface": "#f8f9ff",
        "primary-fixed-dim": "#b0c8eb",
        "surface-variant": "#d3e4fe",
        "on-secondary-fixed-variant": "#004b73",
        "background": "#f8f9ff",
        "on-primary-fixed": "#001c37",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#eff4ff",
        "on-primary-fixed-variant": "#314865",
        "on-background": "#0b1c30",
        "on-primary-container": "#768dad",
        "surface-bright": "#f8f9ff",
        "primary": "#000f22",
        "surface-dim": "#cbdbf5",
        "tertiary-container": "#002a26",
        "primary-container": "#0a2540",
        "inverse-on-surface": "#eaf1ff",
        "tertiary-fixed": "#89f5e7",
        "on-secondary-fixed": "#001d31",
        "outline": "#74777e",
        "secondary-fixed": "#cce5ff",
        "error": "#ba1a1a",
        "on-surface-variant": "#43474d",
        "primary-fixed": "#d2e4ff",
        "tertiary-fixed-dim": "#6bd8cb",
        "outline-variant": "#c4c6ce",
        "surface-tint": "#49607e",
        "inverse-primary": "#b0c8eb",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#93ccff",
        "surface-container-high": "#dce9ff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "secondary": "#006398",
        "surface-container": "#e5eeff",
        "secondary-container": "#5bb8fe",
        "surface-container-highest": "#d3e4fe",
        "on-surface": "#0b1c30",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#005049"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-md": "0.75rem",
        "gutter": "1rem",
        "margin": "1.5rem",
        "space-xs": "0.25rem",
        "space-xl": "1.5rem",
        "space-2xl": "2rem",
        "gutter-lg": "1.5rem",
        "space-sm": "0.5rem",
        "space-lg": "1rem",
        "margin-lg": "2rem"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "data-mono": ["Inter"],
        "headline-md": ["Inter"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-sm": ["Inter"],
        "body-sm": ["Inter"],
        "title": ["Inter"],
        "label-md": ["Inter"],
        "display": ["Inter"]
      },
      fontSize: {
        "body-lg": ["1rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "headline-lg": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "data-mono": ["0.8125rem", { lineHeight: "1.125rem", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-md": ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-sm": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        "headline-sm": ["1.125rem", { lineHeight: "1.5rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["0.75rem", { lineHeight: "1rem", fontWeight: "400" }],
        "title": ["1rem", { lineHeight: "1.5rem", letterSpacing: "-0.005em", fontWeight: "600" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.025em", fontWeight: "600" }],
        "display": ["2rem", { lineHeight: "2.5rem", letterSpacing: "-0.025em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
